# -------------------
# Tmux Configurations
# -------------------

# Set correct colors for zsh in tmux
set -g default-terminal screen-256color

# Set <leader> to <Ctrl>+<s>
set -g prefix C-s

# Bring back <Ctrl>+l to clear the screen with <leader> prefix
bind C-l send-keys 'C-l'

# Make the cursor in Neovim change from rectangle to pipe 
# when switching between normal and iksert mode
# -- must be single ' '!
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# Reload tmux config
unbind r
bind r source-file $HOME/.tmux.conf \; display "Reloaded tmux configuration"

# Activate mouse mode
set -g mouse on

# Activate Vi mode
set-window-option -g mode-keys vi

# Split window to panes with <leader> like in nvim using `v` and `s`
unbind v
unbind s
unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# Move between windows with Vi-like keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Create tabs
unbind c
bind t new-window -c "#{pane_current_path}"

# Make tab index start at 1
set -g base-index 1
set-window-option -g pane-base-index 1

# Rename tab
unbind n
bind n command-prompt "rename-window '%%'"

# Reduce Vi <esc> delay
set-option -sg escape-time 0

# Make the status bar on the top
set-option -g status-position top

# Load plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'fabioluciano/tmux-tokyo-night'

#
# Plugin settings
#

# Tokyo Night Theme configuration
set -g @theme_variation 'night'
set -g @theme_left_separator ''
set -g @theme_right_separator ''

# Bootstrap TPM 
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

run "~/.tmux/plugins/tpm/tpm"
